### ISSUE TITLE
Improve documentation 

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_documentation#145]
### Objective

Modify/improve documentation to make it more user-friendly for new users, so its testing and adoption are easier.

https://maliput.readthedocs.io/en/latest/index.html

### Tasks

- [ ] Create maliput backends section:
     - Comment about how maliput propose an API
     - Comment the available maliput backends
     - Comment about how to rely on maliput_sparse in order to create a maliput backend
     - Maliput dragway and multilane aren’t being used and they work mostly as examples on how to build their own backends
- [ ] Modify tutorial section by applications
     - Mention the applications that are offered by maliput_integration:
     - Mention that some packages offer applications that are particular to their packages and list them here. (maliput malidrive apps.)   
- [ ] Installation process: https://maliput.readthedocs.io/en/latest/installation.html
      - Keep it simple: Guide people to install maliput and maliput_malidrive. Refer people to investigate other backends (via the maliput backends section.)
      - Focus the getting started documentation to use maliput malidrive
      - When building from source? Also use as example maliput malidrive. Otherwise we are pointing the people to install the entire maliput ecosystem just when they are trying to understand the tool.
 - [ ] Move all delphyne related packages (also drake vendor) into another section (like `Related Projects`). So we can dissociate them from maliput base stuff as they probably won't use delphyne.
 - [ ] Create a separate section only for the `maliput_viz`  tool so people use it as they investigate about maliput. Visualization aid is essential for understanding.
 - [ ] Create an example on how OpenDRIVE maps are used via maliput_malidrive and how you can add more rule and semantic information into road network via maliput api.

**Comment by francocipollone** [comment]
I'd like we use this issue to propose documentation changes that permits new user to get started in an easier way.

I dropped some proposals in the issue description that I will tackle one by one.
We can discuss more stuff in this issue and update the above list.
I'd like to hear your ideas @agalbachicar @stonier in case you have some.
