### ISSUE TITLE
[META] Set up sphinx documentation generator

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_documentation#4]
Meta issue to track the efforts of adding [sphinx](https://www.sphinx-doc.org/en/master/index.html) documentation generator.

### 1 - Basic sphinx setup
 - [x] integrate with CMake and generate a default index page. #5 

### 2 - Structure
 - [x] Add an structure: #5 
    - Installation & quickstart guide
    - Developer guidelines
    - Contributing
    - Gallery
    - Documentation

### 3 - Complete pages
- Installation & quickstart guide
  - [ ] Complete
- Developer guidelines
  - [x] Complete #18 
- Contributing 
  - [ ] Complete
- Gallery #3 
  - [x] Add GIFs/videos representing the supported features. #7 
- Documentation
  - [x] Brings doxygen documents from `maliput` and `malidrive` #8 
  - [x] Link sphinx to those document in doxygen. #8  

### 4 - Setup GIthub Pages.

_Note: The issue description will change as the work on this front grows._
